### ISSUE TITLE
Getting issues related to stored properties in xcode 14 

### ISSUE THREAD

**Issue by hamzarehan** [mentalfaculty/LLVS#4]
I am getting this error 
"Stored properties cannot be marked potentially unavailable with '@available'"
in Sources/LLVS/Core/StoreCoordinator line number 41 
also in Sources/LLVS/Exchanges/FileSystemExchange line number 21
and Sources/LLVSCloudKit/CloudKitExchange line number 60

**Comment by drewmccormack** [comment]
Thanks for pointing this out. Just pushed up version 0.6.0, which fixes these issues.
