### ISSUE TITLE
Getting deployment target error after the latest changes

### ISSUE THREAD

**Issue by hamzarehan** [mentalfaculty/LLVS#5]
now i'm unable to run this framework on our app having minimum deployment target set to 12.0. Error is :
"Compiling for iOS 12.0, but module 'LLVS' has a minimum deployment target of iOS 13.0"
now what to do ?

**Comment by drewmccormack** [comment]
Ugh. I'm not sure it is really worth me back porting the framework, given it is quite experimental anyway. You might be able to branch off the old version, and simply make the necessary changes to @available to keep it functioning.

**Comment by hamzarehan** [comment]
but we are not willing to make changes in library we just want to add and run this library

**Comment by hamzarehan** [comment]
By the way, before reporting you this issue i managed to run this framework with some fixes. If you give me write access to this repo i will push the changes that solves my issue. But unfortunately we are not willing to make changes in your framwork

**Comment by drewmccormack** [comment]
You can fork the repo, make your changes, and then issue a pull request. I can consider that and see if I think it is a good idea to merge it in.
